name: Sync to Hugging Face Space

on:
  workflow_run:
    workflows: ["Test Models"]       
    types: [completed]
  workflow_dispatch:

jobs:
  sync-to-space:
    # only run if tests passed
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
        
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://brianmorissette:$HF_TOKEN@huggingface.co/spaces/brianmorissette/Case_Study_1_Group_6 main
