name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-space:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
      - uses: actions/checkout@v4
        
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://brianmorissette:$HF_TOKEN@huggingface.co/spaces/brianmorissette/Case_Study_1_Group_6 main

